dist: xenial

language: python

python:
    - "3.7"
    - "3.6"
    - "3.5"
    - "3.4"
    - "3.3"
    - "2.7"
    - "pypy"

install:
    - pip install --upgrade pip
    - pip install safety pre-commit
    - pip install -r requirements.txt

script:
    - python setup.py test
    - 'if [[ $TRAVIS_PYTHON_VERSION == "3.7" ]]; then git diff --name-only $TRAVIS_COMMIT_RANGE | xargs pre-commit run --files; fi'
    - safety check
